version: '3.9'
services:
  mongodb:
    image: mongo:latest
    # ports:
    #   - "27017:27017"
    expose:
      - 27017
    volumes:
      - dbdata6:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - default
  
  web:
    image: vms-frontend:latest
    build:
      context: ./vms-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    restart: always
    # environment:
    #   - GITLAB_ID=
    #   - GITLAB_SECRET=
    #   - MOGODB_URL=
    #   - MOGODB_DBNAME=
    env_file:
      - ./vms-frontend/.env 
    networks:
      - default

volumes:
  dbdata6:

networks:
  default: